name: sherlock
description: Search a list of maps and order the results based on a given priority map, and by match level. Smart search for user search.
version: 0.0.8
homepage: https://github.com/antoninhrlt/sherlock
license: MIT

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
